### ISSUE TITLE
No support for mailcatcher

### ISSUE THREAD

**Issue by leandersikma** [leoflapper/mailprovider#1]
This mailprovider works pretty well. I was done in less than three minutes with sending my first email via Sendgrid. So thanks for that!

However, I miss one big thing in this mailprovider.
It doesn't allow me to use a mailserver on my localhost. I can only choose between Sendgrid, Mailgun and Mailchimp, which is fine for production. But on my dev machine I'd love to use Mailcatcher which runs on localhost.

What do you think about that, because right now I have to create a separate mail implementation for my dev environment.

**Comment by leoflapper** [comment]
Glad to hear it works for you!

Good question. I'm planning to implement a SMTP mail service in the mailprovider in the mere future. Then it will be possible to catch your mail on your localhost.
